// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXwhFVlTMukwZBsF2AsJd0jRiBIygmCIY',
    appId: '1:869481097232:web:ba6cbd2f2f7210370b8295',
    messagingSenderId: '869481097232',
    projectId: 'taxi-booking-c03ee',
    authDomain: 'taxi-booking-c03ee.firebaseapp.com',
    storageBucket: 'taxi-booking-c03ee.appspot.com',
    measurementId: 'G-CEDQJYPTGS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_amlH_ZoxxNn13plIOLz6R_T9jODiVgw',
    appId: '1:869481097232:android:27c908244b61862f0b8295',
    messagingSenderId: '869481097232',
    projectId: 'taxi-booking-c03ee',
    storageBucket: 'taxi-booking-c03ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw1Gg2CzCR05w40NlSEnVR8zy_1NPY6wg',
    appId: '1:869481097232:ios:368d78d198a3048a0b8295',
    messagingSenderId: '869481097232',
    projectId: 'taxi-booking-c03ee',
    storageBucket: 'taxi-booking-c03ee.appspot.com',
    androidClientId: '869481097232-13tcip23egtk0jlc5td1dold727d1mqm.apps.googleusercontent.com',
    iosClientId: '869481097232-fin0tl3rs7jbkippcpqqis7cfqjef97d.apps.googleusercontent.com',
    iosBundleId: 'com.sterling.taxi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw1Gg2CzCR05w40NlSEnVR8zy_1NPY6wg',
    appId: '1:869481097232:ios:368d78d198a3048a0b8295',
    messagingSenderId: '869481097232',
    projectId: 'taxi-booking-c03ee',
    storageBucket: 'taxi-booking-c03ee.appspot.com',
    androidClientId: '869481097232-13tcip23egtk0jlc5td1dold727d1mqm.apps.googleusercontent.com',
    iosClientId: '869481097232-fin0tl3rs7jbkippcpqqis7cfqjef97d.apps.googleusercontent.com',
    iosBundleId: 'com.sterling.taxi',
  );
}
